/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MarketRouteImport } from './routes/market'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as ApiPublicDhanCallbackRouteImport } from './routes/api/public/dhan/callback'
import { Route as ApiPublicDhanPostbackRouteImport } from './routes/api/public/dhan/postback'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as LoginRouteImport } from './routes/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDhanCallbackRoute = ApiPublicDhanCallbackRouteImport.update({
  id: '/api/public/dhan/callback',
  path: '/api/public/dhan/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDhanPostbackRoute = ApiPublicDhanPostbackRouteImport.update({
  id: '/api/public/dhan/postback',
  path: '/api/public/dhan/postback',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/journal': typeof JournalRoute
  '/market': typeof MarketRoute
  '/risk': typeof RiskRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/api/public/dhan/callback': typeof ApiPublicDhanCallbackRoute
  '/api/public/dhan/postback': typeof ApiPublicDhanPostbackRoute
  '/agents': typeof AgentsRoute
  '/architecture': typeof ArchitectureRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/journal': typeof JournalRoute
  '/market': typeof MarketRoute
  '/risk': typeof RiskRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/api/public/dhan/callback': typeof ApiPublicDhanCallbackRoute
  '/api/public/dhan/postback': typeof ApiPublicDhanPostbackRoute
  '/agents': typeof AgentsRoute
  '/architecture': typeof ArchitectureRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/journal': typeof JournalRoute
  '/market': typeof MarketRoute
  '/risk': typeof RiskRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/api/public/dhan/callback': typeof ApiPublicDhanCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/journal'
    | '/market'
    | '/risk'
    | '/scanner'
    | '/settings'
    | '/signals'
    | '/api/public/dhan/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/journal'
    | '/market'
    | '/risk'
    | '/scanner'
    | '/settings'
    | '/signals'
    | '/api/public/dhan/callback'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/journal'
    | '/market'
    | '/risk'
    | '/scanner'
    | '/settings'
    | '/signals'
    | '/api/public/dhan/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  JournalRoute: typeof JournalRoute
  MarketRoute: typeof MarketRoute
  RiskRoute: typeof RiskRoute
  ScannerRoute: typeof ScannerRoute
  SettingsRoute: typeof SettingsRoute
  SignalsRoute: typeof SignalsRoute
  ApiPublicDhanCallbackRoute: typeof ApiPublicDhanCallbackRoute
  ApiPublicDhanPostbackRoute: typeof ApiPublicDhanPostbackRoute
  AgentsRoute: typeof AgentsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dhan/callback': {
      id: '/api/public/dhan/callback'
      path: '/api/public/dhan/callback'
      fullPath: '/api/public/dhan/callback'
      preLoaderRoute: typeof ApiPublicDhanCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dhan/postback': {
      id: '/api/public/dhan/postback'
      path: '/api/public/dhan/postback'
      fullPath: '/api/public/dhan/postback'
      preLoaderRoute: typeof ApiPublicDhanPostbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  JournalRoute: JournalRoute,
  MarketRoute: MarketRoute,
  RiskRoute: RiskRoute,
  ScannerRoute: ScannerRoute,
  SettingsRoute: SettingsRoute,
  SignalsRoute: SignalsRoute,
  ApiPublicDhanCallbackRoute: ApiPublicDhanCallbackRoute,
  ApiPublicDhanPostbackRoute: ApiPublicDhanPostbackRoute,
  AgentsRoute: AgentsRoute,
  ArchitectureRoute: ArchitectureRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
